### ISSUE TITLE
Bug in code (for Python 3) leads to obvious distortion in images

### ISSUE THREAD

**Issue by philtbrill** [djrobin17/image-stego-tool#1]
This might be a python 2 to python 3 thing, but there is a bug in the code that leads to really obviously distorted images (especially obvious where there is a dark background to the image).

Because bin() does not pad with leading zeroes, for small pixel values, you aren't changing only the LSB
e.g. take a pixel value of 17 - the output of bin(17) is 0b10001, and when you take the [2:9] slice of this you get 10001. The new LSB is added to the end of this, so you end up with 100010 or 100011 - which is 34 or 35 so very different from 17! 

I'm sure there is a simpler solution, but the below code works :-)

`array[p][q] = int(bin(array[p][q])[2:].zfill(8)[:7] + b_message[index], 2)`

i.e. convert to binary, remove 0b from start, pad with leading zeroes, then remove LSB

Thanks for the code - was very useful - even if it did drive me slightly nuts debugging my weirdly striped images :-)

**Comment by philtbrill** [comment]
Code also underestimates how much data can be fitted inside the image.

```
total_pixels = array.size//n

if req_pixels > (total_pixels):
		print("ERROR: Need larger file size")
```
total_pixels is the number of pixels in the image... The amount of data that you can fit is three times this (for an RGB image anyway) as you can get one bit of data on each channel. So correct code is:

```
total_pixels = array.size//n

if req_pixels > (total_pixels * 3):
		print("ERROR: Need larger file size")
```

**Comment by syreal17** [comment]
@philtbrill You're a lifesaver! I'm making this presentation on steganography and I went to all this trouble illustrating that the LSB is a true covert channel, just to see my favorite python tool actually leave behind visual artifacts!

Thanks so much, your fix worked perfectly, first time.

**Comment by philtbrill** [comment]
Glad it helped - it was obviously worth posting the update :-)
